name: scopo
description: "A Flutter package for managing scopes and dependency injection within the widget tree"
version: 0.2.2
homepage: https://github.com/vi-k/scopo

environment:
  sdk: ^3.1.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
#flutter:

