name: scopo
description: "A package for creating scopes in a widget tree and providing dependencies"
version: 0.1.3
homepage: https://github.com/vi-k/scopo

environment:
  sdk: ^3.1.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

#flutter:

