name: scopo_demo
description: "A demo for scopo"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.1.0

dependencies:
  ansi_escape_codes: ^2.1.0
  bloc: ^9.1.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_markdown_plus: ^1.0.5
  flutter_syntax_view: ^4.1.7
  pkglog: ^0.1.1
  scopo:
    path: ../..
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
