name: minimal
description: "Minimal scopo demo"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.1.0

dependencies:
  ansi_escape_codes: ^2.1.0
  flutter:
    sdk: flutter
  pkglog: ^0.1.1
  scopo:
    path: ../..
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
